travis:
  secure:
    BINSTAR_TOKEN: w73EA5TTw0EUlC/RHyio1QpZUhqCE9TnnJ5VwpAYbsPWiXI7SZo067fh5AJ5ZzXLQDeQNsmXvrk25RVOBWedPhgZkHoVlWkTa+/L6GBIAQE4zRXUV0jzVclE2ryE8uOcqW7qxbk96XHWOnLoVh4b/n8XIsCWa09jLkrrcxLQBKQFSt6lVChI9jAm2iPcbOADG0dZi7eX/4x3hROmTt6LlMgxUmlqTw/+oSuD7lywQ6xBGx0yvjnEsRR3ojPzfX9HqB+ictMLntdr9jjDoi29V7FiZcUrBaZnLcsCsuMKvb2gylcBrPr15a6l6HgDv6rIme3gAAvYElYPAyAh1K2YGp7DKz8Li3PPQLhPV5D9UW267ZT6JqdayWc86sDefZjzi7uk8Y3UMMRsHwVw5L0XNKe0grO+vR2NmL6Vlo2yjb47OgFN6NwWzy+HkG+l4IzYeJLedhPFub2ICD+P8wC1uRxv3W5vvcLS66CIOh02G8oxNQVZUZkPUBS0acy+ouA4jpZowPJnd5zJ/6pUEtKBos/fEMFRWhE4l9aaUqY0tYAIh8yFqIik7bp1Fo8FWNqPwS6eeOlfRak6ok1wG3nrn084kOkvTPIS6Aj5HROMr1gYKMF/Ek/FOR4k7hSeDfsgh0bg4ruzCS5igpDs79ne8O8ZXrW9FxNmGdQVmATEGs4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
